spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.229:3306/cpecmcr?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 1qaz@WSX
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

logging:
  level:
    org.mybatis: debug
    com.yu.repository: debug #dao的路径
mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.yu.domain
server:
  port: 8081