package com.yu.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2019-03-07T11:22:59.921+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "CcCodingService", 
                  wsdlLocation = "http://localhost:8080/service/ccCoding?wsdl",
                  targetNamespace = "http://service.yu.com") 
public class CcCodingService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.yu.com", "CcCodingService");
    public final static QName CcCodingServiceImplPort = new QName("http://service.yu.com", "CcCodingServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/service/ccCoding?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CcCodingService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/service/ccCoding?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CcCodingService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CcCodingService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CcCodingService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CcCodingService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CcCodingService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CcCodingService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CcCodingService
     */
    @WebEndpoint(name = "CcCodingServiceImplPort")
    public CcCodingService getCcCodingServiceImplPort() {
        return super.getPort(CcCodingServiceImplPort, CcCodingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CcCodingService
     */
    @WebEndpoint(name = "CcCodingServiceImplPort")
    public CcCodingService getCcCodingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CcCodingServiceImplPort, CcCodingService.class, features);
    }

}
